/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024grupp18;

import java.util.HashMap;
import oru.inf.InfDB;
import java.util.ArrayList;

/**
 *
 * @author alex
 */
public class Avdelning extends javax.swing.JFrame {

    private InfDB idb;
    private String aid;
    private String avdid;

    /**
     * Creates new form Avdelning
     */
    public Avdelning(InfDB idb, String avdid, String aid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        this.avdid = avdid;
        fyllCBAnstalld();
        this.setLocationRelativeTo(null);
    }

    //CB = combobox
    private void fyllCBAnstalld() {
        try {
            String sqlFraga = "SELECT * FROM anstalld WHERE avdelning = (SELECT avdelning FROM anstalld WHERE aid = " + aid + ")";
            System.out.println(sqlFraga);
            ArrayList<HashMap<String, String>> anstalldNamnLista = idb.fetchRows(sqlFraga);
            for (HashMap<String, String> ettNamn : anstalldNamnLista) {
                String fornamn = ettNamn.get("fornamn");
                String efternamn = ettNamn.get("efternamn");
                cbAvdAnstalld.addItem(fornamn + " " + efternamn);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTillbakaAvd = new javax.swing.JButton();
        lblAvdelningRuta = new javax.swing.JLabel();
        cbAvdAnstalld = new javax.swing.JComboBox<>();
        lblEpostAvd = new javax.swing.JLabel();
        lblTnrAvd = new javax.swing.JLabel();
        tfTnrAvd = new javax.swing.JTextField();
        tfEpostAvd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTillbakaAvd.setText("Tillbaka");
        btnTillbakaAvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaAvdActionPerformed(evt);
            }
        });

        lblAvdelningRuta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAvdelningRuta.setText("Avdelning");

        cbAvdAnstalld.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj anställd" }));
        cbAvdAnstalld.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbAvdAnstalldPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        lblEpostAvd.setText("E-post");

        lblTnrAvd.setText("Telefonnummer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvdelningRuta)
                    .addComponent(btnTillbakaAvd)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTnrAvd)
                            .addComponent(lblEpostAvd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEpostAvd, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(tfTnrAvd)))
                    .addComponent(cbAvdAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvdelningRuta)
                .addGap(21, 21, 21)
                .addComponent(cbAvdAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTnrAvd)
                    .addComponent(tfTnrAvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpostAvd, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEpostAvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnTillbakaAvd)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaAvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaAvdActionPerformed
        this.dispose();
        Meny nyMeny = new Meny(idb, aid, avdid);
        nyMeny.setVisible(true);
    }//GEN-LAST:event_btnTillbakaAvdActionPerformed

    private void cbAvdAnstalldPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbAvdAnstalldPopupMenuWillBecomeInvisible
        String anstalld = cbAvdAnstalld.getSelectedItem().toString();
        // WHERE anstalld.avdelning = " + avdid + " AND projektnamn = '" + avdProj + "'";
        try {
            String sqlFraga = "SELECT * FROM avdelning JOIN anstalld ON anstalld.avdelning = avdid "
                    + "WHERE avdid = " + avdid + " AND CONCAT(fornamn, ' ', efternamn) = '" + anstalld + "'";
            System.out.println(sqlFraga);
            HashMap<String, String> avdelning = idb.fetchRow(sqlFraga);
            tfTnrAvd.setText(avdelning.get("telefon"));
            tfTnrAvd.setEditable(false);
            tfEpostAvd.setText(avdelning.get("epost"));
            tfEpostAvd.setEditable(false);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cbAvdAnstalldPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbakaAvd;
    private javax.swing.JComboBox<String> cbAvdAnstalld;
    private javax.swing.JLabel lblAvdelningRuta;
    private javax.swing.JLabel lblEpostAvd;
    private javax.swing.JLabel lblTnrAvd;
    private javax.swing.JTextField tfEpostAvd;
    private javax.swing.JTextField tfTnrAvd;
    // End of variables declaration//GEN-END:variables
}
