/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024grupp18;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JTable;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import ngo2024grupp18.Validering;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author User
 */
public class FiltreraStatus extends javax.swing.JFrame {

    private InfDB idb;
    private String aid;
    private String avdid;

    /**
     * Creates new form FiltreraStatus
     */
    public FiltreraStatus(InfDB idb, String aid, String avdid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        this.avdid = avdid;
        Fyllcb();
        this.setLocationRelativeTo(null); //Används för att centrera JFrameForm i mitten av skärmen.
    }

    private void Fyllcb() {
        cbStatus.addItem("Pågående");
        cbStatus.addItem("Planerat");
        cbStatus.addItem("Avslutat");

        cbStatus.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
            }
        });
    }

    public class CenterRenderer extends DefaultTableCellRenderer {

        public CenterRenderer() {
            setHorizontalAlignment(CENTER);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabell = new javax.swing.JTable();
        btnTillbakaStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrera efter status på min avdelning" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        tblTabell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Projekt-ID", "Projektnamn", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTabell);

        btnTillbakaStatus.setText("Tillbaka");
        btnTillbakaStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTillbakaStatus)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnTillbakaStatus)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        String avdelningsID = this.avdid;
        String kollaStatus = (String) cbStatus.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) tblTabell.getModel();

// Använder CenterRenderer för att centrera värdena som vi får i tabellen till mitten.
        CenterRenderer centerRenderer = new CenterRenderer();

        for (int i = 0; i < tblTabell.getColumnCount(); i++) {
            tblTabell.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        try {
            model.setRowCount(0); // Rensar tabellen innan vi fyller på med ny data, när vi väljer ett annat värde i vår JComboBox.

            String sqlFraga = "SELECT DISTINCT projekt.pid, projektnamn, status "
                    + "FROM projekt "
                    + "JOIN ngo_2024.ans_proj ON ans_proj.pid = projekt.pid "
                    + "JOIN ngo_2024.anstalld ON anstalld.aid = ans_proj.aid "
                    + "WHERE anstalld.avdelning = " + avdelningsID
                    + " AND status = '" + kollaStatus + "'";

            ArrayList<HashMap<String, String>> tabellLista = idb.fetchRows(sqlFraga);

            for (HashMap<String, String> rad : tabellLista) {
                model.addRow(new Object[]{
                    rad.get("pid"),
                    rad.get("projektnamn"),
                    rad.get("status")
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cbStatusActionPerformed

    private void btnTillbakaStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaStatusActionPerformed
        this.toBack();
        Projekt nyttProjekt = new Projekt(idb, aid, avdid);
        nyttProjekt.setVisible(true);
        nyttProjekt.toFront();
    }//GEN-LAST:event_btnTillbakaStatusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbakaStatus;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabell;
    // End of variables declaration//GEN-END:variables
}
