/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024grupp18;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JTable;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author User
 */
public class FiltreraStatus extends javax.swing.JFrame {

    private InfDB idb;
    private String pid;
    private String aid;
    private String avdid;

    /**
     * Creates new form FiltreraStatus
     */
    public FiltreraStatus(InfDB idb, String pid, String aid, String avdid) {
        initComponents();
        this.idb = idb;
        this.pid = pid;
        this.aid = aid;
        this.avdid = avdid;
        Fyllcb();
    }

    FiltreraStatus(InfDB idb, String aid, String avdid) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void Fyllcb() {
        cbStatus.addItem("Pågående");
        cbStatus.addItem("Planerat");
        cbStatus.addItem("Avslutat");

        cbStatus.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
            }
        });
    }

    public class CenterRenderer extends DefaultTableCellRenderer {

        public CenterRenderer() {
            setHorizontalAlignment(CENTER);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabell = new javax.swing.JTable();
        btnTillbakaStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrera efter status" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        tblTabell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Projekt-ID", "Projektnamn", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTabell);

        btnTillbakaStatus.setText("Tillbaka");
        btnTillbakaStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTillbakaStatus)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
HEAD
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnTillbakaStatus)
                .addGap(25, 25, 25))

                .addGap(18, 18, 18)
                .addComponent(btnTillbakaStatus)
                .addContainerGap(44, Short.MAX_VALUE))
 5275c0ccaa982fc07bb583e8cb8ed0322e96dc6a
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        String kollaStatus = (String) cbStatus.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) tblTabell.getModel();

// Använder CenterRenderer för att centrera värdena i tabellen
        CenterRenderer centerRenderer = new CenterRenderer();
        for (int i = 0; i < tblTabell.getColumnCount(); i++) {
            tblTabell.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        try {
            model.setRowCount(0);

            if (kollaStatus.equals("Pågående")) {
                String sqlFraga2 = "SELECT COUNT(status) FROM projekt WHERE status = 'Pågående';";
                String rowCount = idb.fetchSingle(sqlFraga2);
                int rowCountNumber = Integer.parseInt(rowCount);

                String sqlFraga = "SELECT pid, projektnamn, status FROM projekt WHERE status = 'Pågående'";
                ArrayList<HashMap<String, String>> tabellLista = idb.fetchRows(sqlFraga);

                System.out.println(sqlFraga2);
                System.out.println(rowCount);

                for (int i = 0; i < tabellLista.size(); i++) {
                    HashMap<String, String> rad = tabellLista.get(i);
                    model.addRow(new Object[]{rad.get("pid"), rad.get("projektnamn"), rad.get("status")});
                    System.out.println(i);
                }
            } else if (kollaStatus.equals("Planerat")) {
                String sqlFraga2 = "SELECT COUNT(status) FROM projekt WHERE status = 'Planerat';";
                String rowCount = idb.fetchSingle(sqlFraga2);
                int rowCountNumber = Integer.parseInt(rowCount);

                String sqlFraga = "SELECT pid, projektnamn, status FROM projekt WHERE status = 'Planerat'";
                ArrayList<HashMap<String, String>> tabellLista = idb.fetchRows(sqlFraga);

                System.out.println(sqlFraga2);
                System.out.println(rowCount);

                for (int i = 0; i < tabellLista.size(); i++) {
                    HashMap<String, String> rad = tabellLista.get(i);
                    model.addRow(new Object[]{rad.get("pid"), rad.get("projektnamn"), rad.get("status")});
                    System.out.println(i);
                }
            } else if (kollaStatus.equals("Avslutat")) {
                String sqlFraga2 = "SELECT COUNT(status) FROM projekt WHERE status = 'Avslutat';";
                String rowCount = idb.fetchSingle(sqlFraga2);
                int rowCountNumber = Integer.parseInt(rowCount);

                String sqlFraga = "SELECT pid, projektnamn, status FROM projekt WHERE status = 'Avslutat'";
                ArrayList<HashMap<String, String>> tabellLista = idb.fetchRows(sqlFraga);

                System.out.println(sqlFraga2);
                System.out.println(rowCount);

                for (int i = 0; i < tabellLista.size(); i++) {
                    HashMap<String, String> rad = tabellLista.get(i);
                    model.addRow(new Object[]{rad.get("pid"), rad.get("projektnamn"), rad.get("status")});
                    System.out.println(i);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cbStatusActionPerformed

    private void btnTillbakaStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaStatusActionPerformed
        this.toBack();

        Projekt nyttProjekt = new Projekt(idb,aid, avdid);
        nyttProjekt.setVisible(true);
        nyttProjekt.toFront();

        Projekt nyttProject = new Projekt(idb, aid, avdid);
        nyttProject.setVisible(true);
        nyttProject.toFront();
 5275c0ccaa982fc07bb583e8cb8ed0322e96dc6a
    }//GEN-LAST:event_btnTillbakaStatusActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FiltreraStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FiltreraStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FiltreraStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FiltreraStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FiltreraStatus().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbakaStatus;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabell;
    // End of variables declaration//GEN-END:variables
}
