/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024grupp18;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static ngo2024grupp18.Validering.*;
import oru.inf.InfDB;

/**
 *
 * @author ellenor
 */
public class LaggTillLand extends javax.swing.JFrame {

    private InfDB idb;
    private String aid;
    private String avdid;

    /**
     * Creates new form LaggTillLand
     */
    public LaggTillLand(InfDB idb, String aid, String avdid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        this.avdid = avdid;
        this.setLocationRelativeTo(null);
        LaggaTillNyLid();
    }

    //Genererar ny land-id vid tillägg av nytt land genom att +1 på högsta befintliga land-id
    //Valt att inte validera lägg till land (lid) då det genereras automatiskt genom att alltid öka med 1 från det högsta befintliga värdet, det är ingenting som man manuellt matar in
    private String LaggaTillNyLid() {
        String nyLid = null;
        try {
            //SQL-fråga för att hämta ut största land-id (lid) som finns i land
            String sqlFragaHogstLid = "SELECT max(lid) FROM land";
            System.out.println(sqlFragaHogstLid);
            //Hämtar ut resultatet från sql-frågan i en sträng 
            String hogstLidDB = idb.fetchSingle(sqlFragaHogstLid);
            //Konverterar strängen med högst lid till en int
            int hogstLidInt = Integer.parseInt(hogstLidDB);
            int nyLidInt = hogstLidInt + 1;
            System.out.println(nyLidInt);
            nyLid = Integer.toString(nyLidInt);
            tfLandIDLaggTillLand.setText(nyLid);
            tfLandIDLaggTillLand.setEditable(false);
            lblLandIDLaggTillLand.requestFocus();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return nyLid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLaggTillLand = new javax.swing.JLabel();
        lblLandIDLaggTillLand = new javax.swing.JLabel();
        lblNamnLaggTillLand = new javax.swing.JLabel();
        lblSprakLaggTillLand = new javax.swing.JLabel();
        lblValutaLaggTillLand = new javax.swing.JLabel();
        lblTidszonLaggTillLand = new javax.swing.JLabel();
        lblPolitiskStrukturLaggTillLand = new javax.swing.JLabel();
        lblEkonomiLaggTillLand = new javax.swing.JLabel();
        tfLandIDLaggTillLand = new javax.swing.JTextField();
        tfNamnLaggTillLand = new javax.swing.JTextField();
        tfSprakLaggTillLand = new javax.swing.JTextField();
        tfValutaLaggTillLand = new javax.swing.JTextField();
        tfTidszonLaggTillLand = new javax.swing.JTextField();
        tfPolitiskStrukturLaggTillLand = new javax.swing.JTextField();
        tfEkonomiLaggTillLand = new javax.swing.JTextField();
        btnTillbakaLaggTillLand = new javax.swing.JButton();
        btnSparaLaggTillLand = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLaggTillLand.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblLaggTillLand.setText("Lägg till land ");

        lblLandIDLaggTillLand.setText("Land-ID");

        lblNamnLaggTillLand.setText("Namn");

        lblSprakLaggTillLand.setText("Språk");

        lblValutaLaggTillLand.setText("Valuta");

        lblTidszonLaggTillLand.setText("Tidszon");

        lblPolitiskStrukturLaggTillLand.setText("Politisk struktur ");

        lblEkonomiLaggTillLand.setText("Ekonomi");

        btnTillbakaLaggTillLand.setText("Tillbaka");
        btnTillbakaLaggTillLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaLaggTillLandActionPerformed(evt);
            }
        });

        btnSparaLaggTillLand.setText("Spara");
        btnSparaLaggTillLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaLaggTillLandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLaggTillLand)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSparaLaggTillLand)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPolitiskStrukturLaggTillLand)
                                            .addComponent(lblEkonomiLaggTillLand))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfEkonomiLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfPolitiskStrukturLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblLandIDLaggTillLand)
                                                .addComponent(lblNamnLaggTillLand)
                                                .addComponent(lblSprakLaggTillLand)
                                                .addComponent(lblValutaLaggTillLand)
                                                .addComponent(lblTidszonLaggTillLand))
                                            .addGap(60, 60, 60)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfValutaLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfTidszonLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfSprakLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfNamnLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfLandIDLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnTillbakaLaggTillLand)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblLaggTillLand)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLandIDLaggTillLand)
                    .addComponent(tfLandIDLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamnLaggTillLand)
                    .addComponent(tfNamnLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSprakLaggTillLand)
                    .addComponent(tfSprakLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValutaLaggTillLand)
                    .addComponent(tfValutaLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTidszonLaggTillLand)
                    .addComponent(tfTidszonLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPolitiskStrukturLaggTillLand)
                    .addComponent(tfPolitiskStrukturLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEkonomiLaggTillLand)
                    .addComponent(tfEkonomiLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbakaLaggTillLand)
                    .addComponent(btnSparaLaggTillLand))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaLaggTillLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaLaggTillLandActionPerformed
        this.dispose();
        Land nyttLand = new Land(idb, aid, avdid);
        nyttLand.setVisible(true);
    }//GEN-LAST:event_btnTillbakaLaggTillLandActionPerformed

    private void btnSparaLaggTillLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaLaggTillLandActionPerformed
        //Gör om nya lid från String till int för att kunna lägga in i db
        String nyLidStr = tfLandIDLaggTillLand.getText();
        int nyLid = Integer.parseInt(nyLidStr);

        // kontrollerar om textfields är tomma
        String laggTillNamn = tfNamnLaggTillLand.getText();

        if (laggTillNamn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i namn");
        }

        String laggTillSprak = tfSprakLaggTillLand.getText();

        if (laggTillSprak.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i språk");
        }

        String laggTillValuta = tfValutaLaggTillLand.getText();

        if (laggTillValuta.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i valuta");
        }

        if (!isKorrektValuta(tfValutaLaggTillLand)) {
            return;
        }

        String laggTillTidszon = tfTidszonLaggTillLand.getText();

        if (laggTillTidszon.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i tidszon");
        }

        String laggTillPolitiskStruktur = tfPolitiskStrukturLaggTillLand.getText();

        if (laggTillPolitiskStruktur.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i politisk struktur");
        }
        String laggTillEkonomi = tfEkonomiLaggTillLand.getText();

        if (laggTillEkonomi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i ekonomi");
        }

        try {
            String sqlFraga = "INSERT INTO land (lid, namn, sprak, valuta, tidszon, politisk_struktur, ekonomi) VALUES (" + nyLid + ",'" + laggTillNamn + "', '" + laggTillSprak + "', '" + laggTillValuta + "', '" + laggTillTidszon + "', '" + laggTillPolitiskStruktur + "', '" + laggTillEkonomi + "')";
            idb.insert(sqlFraga);

            JOptionPane.showMessageDialog(null, "Land tillagt");
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnSparaLaggTillLandActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaLaggTillLand;
    private javax.swing.JButton btnTillbakaLaggTillLand;
    private javax.swing.JLabel lblEkonomiLaggTillLand;
    private javax.swing.JLabel lblLaggTillLand;
    private javax.swing.JLabel lblLandIDLaggTillLand;
    private javax.swing.JLabel lblNamnLaggTillLand;
    private javax.swing.JLabel lblPolitiskStrukturLaggTillLand;
    private javax.swing.JLabel lblSprakLaggTillLand;
    private javax.swing.JLabel lblTidszonLaggTillLand;
    private javax.swing.JLabel lblValutaLaggTillLand;
    private javax.swing.JTextField tfEkonomiLaggTillLand;
    private javax.swing.JTextField tfLandIDLaggTillLand;
    private javax.swing.JTextField tfNamnLaggTillLand;
    private javax.swing.JTextField tfPolitiskStrukturLaggTillLand;
    private javax.swing.JTextField tfSprakLaggTillLand;
    private javax.swing.JTextField tfTidszonLaggTillLand;
    private javax.swing.JTextField tfValutaLaggTillLand;
    // End of variables declaration//GEN-END:variables
}
