/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024grupp18;

import oru.inf.InfDB;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author ellenor
 */
public class LaggTillSamarbetspartner extends javax.swing.JFrame {

    private InfDB idb;
    private String aid;
    private String avdid;

    /**
     * Creates new form LaggTillPartner
     */
    public LaggTillSamarbetspartner(InfDB idb, String aid, String avdid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        this.avdid = avdid;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSamarbetspartnerRuta = new javax.swing.JLabel();
        lblProjektIDLaggTillPartner = new javax.swing.JLabel();
        lblNamnLaggTillPartner = new javax.swing.JLabel();
        lblEpostLaggTillPartner = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTnrLaggTillPartner = new javax.swing.JLabel();
        lblAdressLaggTillPartner = new javax.swing.JLabel();
        lblBranchLaggTillPartner = new javax.swing.JLabel();
        lblStadLaggTillPartner = new javax.swing.JLabel();
        tfProjektIDLaggTillPartner = new javax.swing.JTextField();
        tfNamnLaggTillPartner = new javax.swing.JTextField();
        tfKontaktpersonLaggTillPartner = new javax.swing.JTextField();
        tfEpostLaggTillPartner = new javax.swing.JTextField();
        tfTelefonLaggTillPartner = new javax.swing.JTextField();
        tfAdressLaggTillPartner = new javax.swing.JTextField();
        tfBranchLaggTillPartner = new javax.swing.JTextField();
        tfStadLaggTillPartner = new javax.swing.JTextField();
        btnTillbakaLaggTillPartner = new javax.swing.JButton();
        btnSparaLaggTillPartner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSamarbetspartnerRuta.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblSamarbetspartnerRuta.setText("Lägg till samarbetspartner ");

        lblProjektIDLaggTillPartner.setText("Projekt-ID");

        lblNamnLaggTillPartner.setText("Namn");

        lblEpostLaggTillPartner.setText("Kontaktperson");

        jLabel4.setText("E-post");

        lblTnrLaggTillPartner.setText("Telefon");

        lblAdressLaggTillPartner.setText("Adress");

        lblBranchLaggTillPartner.setText("Branch");

        lblStadLaggTillPartner.setText("Stad");

        btnTillbakaLaggTillPartner.setText("Tillbaka");
        btnTillbakaLaggTillPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaLaggTillPartnerActionPerformed(evt);
            }
        });

        btnSparaLaggTillPartner.setText("Spara");
        btnSparaLaggTillPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaLaggTillPartnerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSamarbetspartnerRuta)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProjektIDLaggTillPartner)
                                    .addComponent(lblNamnLaggTillPartner)
                                    .addComponent(lblEpostLaggTillPartner)
                                    .addComponent(jLabel4)
                                    .addComponent(lblTnrLaggTillPartner)
                                    .addComponent(lblAdressLaggTillPartner)
                                    .addComponent(lblBranchLaggTillPartner)
                                    .addComponent(lblStadLaggTillPartner))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfProjektIDLaggTillPartner)
                                    .addComponent(tfNamnLaggTillPartner)
                                    .addComponent(tfKontaktpersonLaggTillPartner)
                                    .addComponent(tfEpostLaggTillPartner)
                                    .addComponent(tfTelefonLaggTillPartner)
                                    .addComponent(tfAdressLaggTillPartner)
                                    .addComponent(tfBranchLaggTillPartner)
                                    .addComponent(tfStadLaggTillPartner, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbakaLaggTillPartner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSparaLaggTillPartner)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblSamarbetspartnerRuta)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektIDLaggTillPartner)
                    .addComponent(tfProjektIDLaggTillPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamnLaggTillPartner)
                    .addComponent(tfNamnLaggTillPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpostLaggTillPartner)
                    .addComponent(tfKontaktpersonLaggTillPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfEpostLaggTillPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTnrLaggTillPartner)
                    .addComponent(tfTelefonLaggTillPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdressLaggTillPartner)
                    .addComponent(tfAdressLaggTillPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBranchLaggTillPartner)
                    .addComponent(tfBranchLaggTillPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStadLaggTillPartner)
                    .addComponent(tfStadLaggTillPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbakaLaggTillPartner)
                    .addComponent(btnSparaLaggTillPartner))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaLaggTillPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaLaggTillPartnerActionPerformed
        this.toBack();
        Samarbetspartner nyPartner = new Samarbetspartner(idb, aid, avdid);
        nyPartner.setVisible(true);
        nyPartner.toFront();
        
        
        
    }//GEN-LAST:event_btnTillbakaLaggTillPartnerActionPerformed

    private void btnSparaLaggTillPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaLaggTillPartnerActionPerformed
      
        String laggTillNamn = tfNamnLaggTillPartner.getText();

        if (laggTillNamn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i namn");

        }
        
         String laggTillKontaktperson = tfKontaktpersonLaggTillPartner.getText();

        if (laggTillNamn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i kontaktperson");

        }
        
        
        String laggTillKontaktEpost = tfEpostLaggTillPartner.getText();

        if (laggTillNamn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i E-post");

        }
        
        String laggTillTelefonnummer = tfTelefonLaggTillPartner.getText();

        if (laggTillNamn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i telefonnummer");

        }
        
        String laggTillAdress = tfAdressLaggTillPartner.getText();

        if (laggTillNamn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i adress");

        }
        
        String laggTillBranch = tfBranchLaggTillPartner.getText();

        if (laggTillNamn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i branch");

        }
        
        String laggTillStad = tfStadLaggTillPartner.getText();

        if (laggTillNamn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i stad");

        }
        
        
        
        try{
            
          String projektID = tfProjektIDLaggTillPartner.getText();
          String namn = tfNamnLaggTillPartner.getText();
          String kontaktperson = tfKontaktpersonLaggTillPartner.getText();
          String kontaktEpost = tfEpostLaggTillPartner.getText();
          String telefonnummer = tfTelefonLaggTillPartner.getText();
          String adress = tfAdressLaggTillPartner.getText();
          String branch = tfBranchLaggTillPartner.getText();
          String stad = tfStadLaggTillPartner.getText();
          
          String sqlFraga = " INSERT INTO partner WHERE pid = (pid, namn, sprak, valuta, tidszon, politisk_struktur, ekonomi) VALUES ('" + projektID + "','" + namn + "', '" + kontaktperson + "', '" + kontaktEpost + "', '" + telefonnummer + "', '" + adress + "','" + stad + "', '" + branch + "')";
            idb.insert(sqlFraga);
            
            
        
        }catch(Exception ex){
        
        System.out.println(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_btnSparaLaggTillPartnerActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaLaggTillPartner;
    private javax.swing.JButton btnTillbakaLaggTillPartner;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAdressLaggTillPartner;
    private javax.swing.JLabel lblBranchLaggTillPartner;
    private javax.swing.JLabel lblEpostLaggTillPartner;
    private javax.swing.JLabel lblNamnLaggTillPartner;
    private javax.swing.JLabel lblProjektIDLaggTillPartner;
    private javax.swing.JLabel lblSamarbetspartnerRuta;
    private javax.swing.JLabel lblStadLaggTillPartner;
    private javax.swing.JLabel lblTnrLaggTillPartner;
    private javax.swing.JTextField tfAdressLaggTillPartner;
    private javax.swing.JTextField tfBranchLaggTillPartner;
    private javax.swing.JTextField tfEpostLaggTillPartner;
    private javax.swing.JTextField tfKontaktpersonLaggTillPartner;
    private javax.swing.JTextField tfNamnLaggTillPartner;
    private javax.swing.JTextField tfProjektIDLaggTillPartner;
    private javax.swing.JTextField tfStadLaggTillPartner;
    private javax.swing.JTextField tfTelefonLaggTillPartner;
    // End of variables declaration//GEN-END:variables
}
