/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024grupp18;

import java.util.ArrayList;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author ellenor
 */
public class Land extends javax.swing.JFrame {

    private InfDB idb;
    private String aid;
    private String avdid;

    /**
     * Creates new form Land
     */
    public Land(InfDB idb, String aid, String avdid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        this.avdid = avdid;
        fyllCBLand();
        this.setLocationRelativeTo(null);
    }

    public void fyllCBLand() {
        try {
            String sqlFraga = "SELECT namn FROM land";
            System.out.println(sqlFraga);
            ArrayList<String> projektNamnLista = idb.fetchColumn(sqlFraga);

            for (String ettProjekt : projektNamnLista) {
                cbLand.addItem(ettProjekt);
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTillbakaLand = new javax.swing.JButton();
        lblLandRuta = new javax.swing.JLabel();
        lblLandIDLand = new javax.swing.JLabel();
        lblNamnLand = new javax.swing.JLabel();
        lblSpråkLand = new javax.swing.JLabel();
        lblValutaLand = new javax.swing.JLabel();
        lblTidzonLand = new javax.swing.JLabel();
        lblPolitiskStrukturLand = new javax.swing.JLabel();
        lblEkonomiLand = new javax.swing.JLabel();
        tfLandID = new javax.swing.JTextField();
        tfNamnLand = new javax.swing.JTextField();
        tfSprakLand = new javax.swing.JTextField();
        tfValutaLand = new javax.swing.JTextField();
        tfTidszonLand = new javax.swing.JTextField();
        tfPolitiskStrukturLand = new javax.swing.JTextField();
        tfEkonomiLand = new javax.swing.JTextField();
        btnSparaÄndringarLand = new javax.swing.JButton();
        cbLand = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTillbakaLand.setText("Tillbaka");
        btnTillbakaLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaLandActionPerformed(evt);
            }
        });

        lblLandRuta.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblLandRuta.setText("Land");

        lblLandIDLand.setText("Land-ID");

        lblNamnLand.setText("Namn");

        lblSpråkLand.setText("Språk");

        lblValutaLand.setText("Valuta");

        lblTidzonLand.setText("Tidszon");

        lblPolitiskStrukturLand.setText("Politisk struktur");

        lblEkonomiLand.setText("Ekonomi");

        btnSparaÄndringarLand.setText("Spara ändringar");
        btnSparaÄndringarLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaÄndringarLandActionPerformed(evt);
            }
        });

        cbLand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj " }));
        cbLand.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbLandPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jButton1.setText("Lägg till land");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnTillbakaLand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSparaÄndringarLand)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamnLand)
                            .addComponent(lblSpråkLand)
                            .addComponent(lblValutaLand)
                            .addComponent(lblTidzonLand)
                            .addComponent(lblPolitiskStrukturLand)
                            .addComponent(lblEkonomiLand)
                            .addComponent(lblLandRuta)
                            .addComponent(lblLandIDLand))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfLandID)
                                .addComponent(tfNamnLand)
                                .addComponent(tfSprakLand)
                                .addComponent(tfValutaLand)
                                .addComponent(tfTidszonLand)
                                .addComponent(tfPolitiskStrukturLand)
                                .addComponent(tfEkonomiLand, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addComponent(jButton1))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLandRuta)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLandIDLand)
                    .addComponent(tfLandID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamnLand)
                    .addComponent(tfNamnLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpråkLand)
                    .addComponent(tfSprakLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValutaLand)
                    .addComponent(tfValutaLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTidzonLand)
                    .addComponent(tfTidszonLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPolitiskStrukturLand)
                    .addComponent(tfPolitiskStrukturLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEkonomiLand)
                    .addComponent(tfEkonomiLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSparaÄndringarLand)
                    .addComponent(btnTillbakaLand))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaLandActionPerformed
        this.toBack();
        Projekt nyttProject = new Projekt(idb, aid, avdid);
        nyttProject.setVisible(true);
        nyttProject.toFront();
    }//GEN-LAST:event_btnTillbakaLandActionPerformed

    private void cbLandPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbLandPopupMenuWillBecomeInvisible
        String namnLand = cbLand.getSelectedItem().toString();
        try {
            String sqlFraga = "SELECT * FROM land WHERE namn = '" + namnLand + "'";
            System.out.println(sqlFraga);

            HashMap<String, String> landLista = idb.fetchRow(sqlFraga);
            if (landLista != null) {

                tfLandID.setText(landLista.get("lid"));
                tfNamnLand.setText(landLista.get("namn"));
                tfSprakLand.setText(landLista.get("sprak"));
                tfValutaLand.setText(landLista.get("valuta"));
                tfTidszonLand.setText(landLista.get("tidszon"));
                tfPolitiskStrukturLand.setText(landLista.get("politisk_struktur"));
                tfEkonomiLand.setText(landLista.get("ekonomi"));

            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());

        }


    }//GEN-LAST:event_cbLandPopupMenuWillBecomeInvisible

    private void btnSparaÄndringarLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaÄndringarLandActionPerformed

        String namnLand = cbLand.getSelectedItem().toString();
        try {
            String landID = tfLandID.getText();
            String namn = tfNamnLand.getText();
            String sprak = tfSprakLand.getText();
            String valuta = tfValutaLand.getText();
            String tidszon = tfTidszonLand.getText();
            String politiskStruktur = tfPolitiskStrukturLand.getText();
            String ekonomi = tfEkonomiLand.getText();

            String sqlFraga = "UPDATE land SET lid = " + landID + ", sprak = '" + sprak + "', valuta = '" + valuta + "', tidszon = '" + tidszon + "', ekonomi = '" + ekonomi + "' WHERE namn = '" + namnLand + "'";
            idb.update(sqlFraga);

            JOptionPane.showMessageDialog(null, "Ändring sparad");

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }


    }//GEN-LAST:event_btnSparaÄndringarLandActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LaggTillLand(idb, aid, avdid).setVisible(true);
        setVisible(false);


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaÄndringarLand;
    private javax.swing.JButton btnTillbakaLand;
    private javax.swing.JComboBox<String> cbLand;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblEkonomiLand;
    private javax.swing.JLabel lblLandIDLand;
    private javax.swing.JLabel lblLandRuta;
    private javax.swing.JLabel lblNamnLand;
    private javax.swing.JLabel lblPolitiskStrukturLand;
    private javax.swing.JLabel lblSpråkLand;
    private javax.swing.JLabel lblTidzonLand;
    private javax.swing.JLabel lblValutaLand;
    private javax.swing.JTextField tfEkonomiLand;
    private javax.swing.JTextField tfLandID;
    private javax.swing.JTextField tfNamnLand;
    private javax.swing.JTextField tfPolitiskStrukturLand;
    private javax.swing.JTextField tfSprakLand;
    private javax.swing.JTextField tfTidszonLand;
    private javax.swing.JTextField tfValutaLand;
    // End of variables declaration//GEN-END:variables
}
