/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024grupp18;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author alex
 */
public class MinaProjekt extends javax.swing.JFrame {

    private InfDB idb;
    private String aid;
    private String avdid;

    /**
     * Creates new form MinaProjekt
     */
    public MinaProjekt(InfDB idb, String aid, String avdid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        this.avdid = avdid;
        fyllCBMinaProjekt();
        fyllPaLander();
        fyllPaStatus();
        fyllPaPrioritet();
        fyllCBVäljProjektchef();
        this.setLocationRelativeTo(null);
    }
// Tror inte fyllCBMinaProjekt-metoden funkar nu, kanske för att man måste lägga till ytterligare sql-frågor för att uppdatera andra berörda tabller
    // när man lägger till nytt projekt? D.v.s. ans_proj. Ej gjort detta än!

    public void fyllCBMinaProjekt() {
        try {
            String sqlFraga = "SELECT projektnamn FROM projekt JOIN ans_proj ON ans_proj.pid = projekt.pid WHERE aid = " + aid;
            System.out.println(sqlFraga);
            ArrayList<String> minaProjektLista = idb.fetchColumn(sqlFraga);
            for (String ettProjekt : minaProjektLista) {
                cbMinaProjekt.addItem(ettProjekt);
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTillbakaMinaProj = new javax.swing.JButton();
        lblProjektID = new javax.swing.JLabel();
        tfProjektID = new javax.swing.JTextField();
        lblProjektNamn = new javax.swing.JLabel();
        tfProjektNamn = new javax.swing.JTextField();
        lblBeskrivningProjekt = new javax.swing.JLabel();
        tfBeskrivningProjekt = new javax.swing.JTextField();
        lblStartdatum = new javax.swing.JLabel();
        tfStartdatum = new javax.swing.JTextField();
        lblSlutdatum = new javax.swing.JLabel();
        tfSlutdatum = new javax.swing.JTextField();
        lblKostnad = new javax.swing.JLabel();
        tfKostnad = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        lblPrioProjekt = new javax.swing.JLabel();
        lblProjektchef = new javax.swing.JLabel();
        lblLand = new javax.swing.JLabel();
        btnAndraUppgifterMinaProjekt = new javax.swing.JButton();
        lblMinaProjektRuta = new javax.swing.JLabel();
        cbMinaProjekt = new javax.swing.JComboBox<>();
        btnStatistikMinaProjekt = new javax.swing.JButton();
        cbStatusMinaProjekt = new javax.swing.JComboBox<>();
        cbPrioritetMinaProjekt = new javax.swing.JComboBox<>();
        cbProjektchefMinaProjekt = new javax.swing.JComboBox<>();
        cbLandMinaProjekt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTillbakaMinaProj.setText("Tillbaka");
        btnTillbakaMinaProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaMinaProjActionPerformed(evt);
            }
        });

        lblProjektID.setText("Projekt-ID");

        lblProjektNamn.setText("Projektnamn");

        lblBeskrivningProjekt.setText("Beskrivning");

        lblStartdatum.setText("Startdatum");

        lblSlutdatum.setText("Slutdatum");

        lblKostnad.setText("Kostnad");

        lblStatus.setText("Status");

        lblPrioProjekt.setText("Prioritet");

        lblProjektchef.setText("Projektchef");

        lblLand.setText("Land");

        btnAndraUppgifterMinaProjekt.setText("Ändra uppgifter");
        btnAndraUppgifterMinaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraUppgifterMinaProjektActionPerformed(evt);
            }
        });

        lblMinaProjektRuta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMinaProjektRuta.setText("Mina projekt");

        cbMinaProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj ett projekt" }));
        cbMinaProjekt.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbMinaProjektPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btnStatistikMinaProjekt.setText("Visa statistik");
        btnStatistikMinaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistikMinaProjektActionPerformed(evt);
            }
        });

        cbStatusMinaProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ändra status" }));

        cbPrioritetMinaProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ändra prioritet" }));

        cbProjektchefMinaProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ändra projektchef", " " }));

        cbLandMinaProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ändra land" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cbMinaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStatistikMinaProjekt)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblSlutdatum)
                                                .addComponent(lblLand)
                                                .addComponent(lblProjektchef)
                                                .addComponent(lblPrioProjekt)
                                                .addComponent(lblStatus)
                                                .addComponent(lblKostnad)
                                                .addComponent(lblStartdatum))
                                            .addComponent(lblBeskrivningProjekt))
                                        .addComponent(lblProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblProjektID, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTillbakaMinaProj)
                                        .addGap(46, 46, 46)))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfProjektNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(tfBeskrivningProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(tfProjektID)
                                    .addComponent(tfStartdatum)
                                    .addComponent(tfSlutdatum)
                                    .addComponent(tfKostnad)
                                    .addComponent(cbStatusMinaProjekt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbPrioritetMinaProjekt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbProjektchefMinaProjekt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbLandMinaProjekt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblMinaProjektRuta, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(118, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAndraUppgifterMinaProjekt)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblMinaProjektRuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbMinaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProjektID)
                            .addComponent(tfProjektID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProjektNamn)
                            .addComponent(tfProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBeskrivningProjekt)
                            .addComponent(tfBeskrivningProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStartdatum)
                            .addComponent(tfStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSlutdatum)
                            .addComponent(tfSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKostnad)
                            .addComponent(tfKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatus)
                            .addComponent(cbStatusMinaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrioProjekt)
                            .addComponent(cbPrioritetMinaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProjektchef)
                            .addComponent(cbProjektchefMinaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLand)
                            .addComponent(cbLandMinaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnStatistikMinaProjekt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndraUppgifterMinaProjekt)
                    .addComponent(btnTillbakaMinaProj))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaMinaProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaMinaProjActionPerformed
        this.toBack();
        Projekt nyttProject = new Projekt(idb, aid, avdid);
        nyttProject.setVisible(true);
        nyttProject.toFront();
    }//GEN-LAST:event_btnTillbakaMinaProjActionPerformed

    private void cbMinaProjektPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbMinaProjektPopupMenuWillBecomeInvisible
        String minaProjektNamn = cbMinaProjekt.getSelectedItem().toString();

        try {
            String sqlFraga1 = "SELECT * FROM projekt JOIN ans_proj ON projekt.pid = ans_proj.pid "
                    + "WHERE ans_proj.aid = " + aid + " AND projektnamn = '" + minaProjektNamn + "'";
            System.out.println(sqlFraga1);
            HashMap<String, String> minaProjekt = idb.fetchRow(sqlFraga1);

            String sqlFraga2 = "SELECT namn FROM land WHERE lid = '" + minaProjekt.get("land") + "'";
            String land = idb.fetchSingle(sqlFraga2);

            String sqlFraga3 = "SELECT fornamn, efternamn FROM anstalld WHERE aid =" + minaProjekt.get("projektchef");
            HashMap<String, String> projektchef = idb.fetchRow(sqlFraga3);

            cbStatusMinaProjekt.setSelectedItem(minaProjekt.get("status"));
            cbPrioritetMinaProjekt.setSelectedItem(minaProjekt.get("prioritet"));
            cbLandMinaProjekt.setSelectedItem(land);
            cbProjektchefMinaProjekt.setSelectedItem(projektchef.get("fornamn") + " " + projektchef.get("efternamn"));

            tfProjektID.setText(minaProjekt.get("pid"));
            tfProjektID.setEditable(false);
            lblProjektID.requestFocus();
            tfProjektNamn.setText(minaProjekt.get("projektnamn"));
            tfProjektNamn.setEditable(false);
            tfBeskrivningProjekt.setText(minaProjekt.get("beskrivning"));
            tfBeskrivningProjekt.setEditable(false);
            tfStartdatum.setText(minaProjekt.get("startdatum"));
            tfStartdatum.setEditable(false);
            tfSlutdatum.setText(minaProjekt.get("slutdatum"));
            tfSlutdatum.setEditable(false);
            tfKostnad.setText(minaProjekt.get("kostnad"));
            tfKostnad.setEditable(false);

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_cbMinaProjektPopupMenuWillBecomeInvisible

    private void btnStatistikMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistikMinaProjektActionPerformed
        new ProjektStatistik(idb, aid, avdid).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnStatistikMinaProjektActionPerformed

    private void btnAndraUppgifterMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraUppgifterMinaProjektActionPerformed
        try {
            String projektId = tfProjektID.getText();
            String projektNamn = tfProjektNamn.getText();
            String projektBeskrivning = tfBeskrivningProjekt.getText();
            String projektStartDatum = tfStartdatum.getText();
            String projektSlutDatum = tfSlutdatum.getText();
            String projektKostnad = tfKostnad.getText();
            String status = cbStatusMinaProjekt.getSelectedItem().toString();
            String prioritet = cbPrioritetMinaProjekt.getSelectedItem().toString();

            String landNamn = cbLandMinaProjekt.getSelectedItem().toString();
            String sqlFragaLandId = "SELECT lid FROM land WHERE namn = '" + landNamn + "'";
            String landId = idb.fetchSingle(sqlFragaLandId);
            
            String projektChefNamn = cbProjektchefMinaProjekt.getSelectedItem().toString();
            String fornamn = projektChefNamn.split(" ")[0];
            String efternamn = projektChefNamn.split(" ")[1];
            String sqlFragaChefId = "SELECT aid FROM anstalld WHERE fornamn = '" + fornamn + "' AND efternamn = '"+efternamn+"'";
            String chefId = idb.fetchSingle(sqlFragaChefId);
            
            String startDatum = "str_to_date('" + projektStartDatum + "', '%Y-%m-%d')";
            String slutDatum = "str_to_date('" + projektSlutDatum + "', '%Y-%m-%d')";
            
            String sqlFraga = "UPDATE projekt SET projektnamn = '" + projektNamn +"', beskrivning = '" + projektBeskrivning + "', startdatum = " + startDatum + ", slutdatum = " + slutDatum + ", kostnad = " + projektKostnad + ", status = '" + status + "', land = "+landId+", projektchef ="+chefId+",prioritet='"+prioritet+"' WHERE pid="+projektId;
            idb.update(sqlFraga);
            
            JOptionPane.showMessageDialog(null, "Ändring sparad");
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }


    }//GEN-LAST:event_btnAndraUppgifterMinaProjektActionPerformed

    private void fyllPaLander() {
        try {
            cbLandMinaProjekt.removeAllItems();
            String sqlFraga4 = "SELECT namn FROM land";
            ArrayList<HashMap<String, String>> allaLander = idb.fetchRows(sqlFraga4);
            for (HashMap<String, String> ettLand : allaLander) {
                cbLandMinaProjekt.addItem(ettLand.get("namn"));
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }

    public void fyllCBVäljProjektchef() {
        try {
            cbProjektchefMinaProjekt.removeAllItems();
            String sqlFraga = "SELECT DISTINCT projektchef FROM projekt";
            System.out.println(sqlFraga);
            ArrayList<String> projektchefIdLista = idb.fetchColumn(sqlFraga);

            for (String enProjektchefId : projektchefIdLista) {
                String sqlFraga1 = "SELECT fornamn, efternamn FROM anstalld WHERE aid =" + enProjektchefId;
                HashMap<String, String> projektchef = idb.fetchRow(sqlFraga1);
                cbProjektchefMinaProjekt.addItem(projektchef.get("fornamn") + " " + projektchef.get("efternamn"));
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());

        }

    }

    private void fyllPaStatus() {
        cbStatusMinaProjekt.removeAllItems();
        cbStatusMinaProjekt.addItem("Planerat");
        cbStatusMinaProjekt.addItem("Pågående");
        cbStatusMinaProjekt.addItem("Avslutat");

    }

    private void fyllPaPrioritet() {
        cbPrioritetMinaProjekt.removeAllItems();
        cbPrioritetMinaProjekt.addItem("Hög");
        cbPrioritetMinaProjekt.addItem("Medel");
        cbPrioritetMinaProjekt.addItem("Låg");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraUppgifterMinaProjekt;
    private javax.swing.JButton btnStatistikMinaProjekt;
    private javax.swing.JButton btnTillbakaMinaProj;
    private javax.swing.JComboBox<String> cbLandMinaProjekt;
    private javax.swing.JComboBox<String> cbMinaProjekt;
    private javax.swing.JComboBox<String> cbPrioritetMinaProjekt;
    private javax.swing.JComboBox<String> cbProjektchefMinaProjekt;
    private javax.swing.JComboBox<String> cbStatusMinaProjekt;
    private javax.swing.JLabel lblBeskrivningProjekt;
    private javax.swing.JLabel lblKostnad;
    private javax.swing.JLabel lblLand;
    private javax.swing.JLabel lblMinaProjektRuta;
    private javax.swing.JLabel lblPrioProjekt;
    private javax.swing.JLabel lblProjektID;
    private javax.swing.JLabel lblProjektNamn;
    private javax.swing.JLabel lblProjektchef;
    private javax.swing.JLabel lblSlutdatum;
    private javax.swing.JLabel lblStartdatum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField tfBeskrivningProjekt;
    private javax.swing.JTextField tfKostnad;
    private javax.swing.JTextField tfProjektID;
    private javax.swing.JTextField tfProjektNamn;
    private javax.swing.JTextField tfSlutdatum;
    private javax.swing.JTextField tfStartdatum;
    // End of variables declaration//GEN-END:variables
}
