/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024grupp18;

import java.util.HashMap;
import oru.inf.InfDB;

/**
 *
 * @author alex
 */
public class Projekt extends javax.swing.JFrame {

    private InfDB idb;
    private String pid;
    private String aid;
    private String avdid;

    /**
     * Creates new form Project
     */
    public Projekt(InfDB idb, String aid, String avdid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        this.avdid = avdid;
        this.setLocationRelativeTo(null);
        MinaUppgifter ny = new MinaUppgifter(idb, aid, avdid);
        btnAllaProjekt.setVisible(false);
        if(ny.isAdmin()) {
             btnAllaProjekt.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProjekt = new javax.swing.JLabel();
        btnAllaProjekt = new javax.swing.JButton();
        btnMinaProjekt = new javax.swing.JButton();
        btnAvdProjekt = new javax.swing.JButton();
        btnLandProjekt = new javax.swing.JButton();
        btnHallbarMalProjekt = new javax.swing.JButton();
        btnSamarbetsPartnersProjekt = new javax.swing.JButton();
        btnTillbakaProjekt = new javax.swing.JButton();
        btnSokAvdProjDatum = new javax.swing.JButton();
        btnFiltreraStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProjekt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblProjekt.setText("Projekt");

        btnAllaProjekt.setText("Alla projekt");
        btnAllaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllaProjektActionPerformed(evt);
            }
        });

        btnMinaProjekt.setText("Mina projekt");
        btnMinaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaProjektActionPerformed(evt);
            }
        });

        btnAvdProjekt.setText("Avdelningens projekt");
        btnAvdProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvdProjektActionPerformed(evt);
            }
        });

        btnLandProjekt.setText("Länder");
        btnLandProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLandProjektActionPerformed(evt);
            }
        });

        btnHallbarMalProjekt.setText("Hållbarhetsmål");
        btnHallbarMalProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHallbarMalProjektActionPerformed(evt);
            }
        });

        btnSamarbetsPartnersProjekt.setText("Samarbetspartners");
        btnSamarbetsPartnersProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSamarbetsPartnersProjektActionPerformed(evt);
            }
        });

        btnTillbakaProjekt.setText("Tillbaka");
        btnTillbakaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaProjektActionPerformed(evt);
            }
        });

        btnSokAvdProjDatum.setText("Sök projekt på datum");
        btnSokAvdProjDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokAvdProjDatumActionPerformed(evt);
            }
        });

        btnFiltreraStatus.setText("Filtrera efter status");
        btnFiltreraStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltreraStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTillbakaProjekt)
                    .addComponent(lblProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinaProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAvdProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSokAvdProjDatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFiltreraStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAllaProjekt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHallbarMalProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(btnLandProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSamarbetsPartnersProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjekt)
                    .addComponent(btnAllaProjekt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinaProjekt)
                    .addComponent(btnLandProjekt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvdProjekt)
                    .addComponent(btnHallbarMalProjekt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSokAvdProjDatum)
                    .addComponent(btnSamarbetsPartnersProjekt))
                .addGap(18, 18, 18)
                .addComponent(btnFiltreraStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(btnTillbakaProjekt)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllaProjektActionPerformed
        new AllaProjekt(idb, aid, avdid).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAllaProjektActionPerformed

    private void btnMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjektActionPerformed
        new MinaProjekt(idb, aid, avdid).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnMinaProjektActionPerformed

    private void btnAvdProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvdProjektActionPerformed
        new AvdelningensProjekt(idb, aid, avdid).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAvdProjektActionPerformed

    private void btnLandProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandProjektActionPerformed
        new Land(idb, aid, avdid).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnLandProjektActionPerformed

    private void btnHallbarMalProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHallbarMalProjektActionPerformed
        new HallbarhetsMal(idb, aid, avdid).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnHallbarMalProjektActionPerformed

    private void btnSamarbetsPartnersProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSamarbetsPartnersProjektActionPerformed
        new Samarbetspartner(idb, aid, avdid).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnSamarbetsPartnersProjektActionPerformed

    private void btnSokAvdProjDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokAvdProjDatumActionPerformed
        this.setVisible(false);
        new SokProjekt(idb, aid, avdid).setVisible(true);
    }//GEN-LAST:event_btnSokAvdProjDatumActionPerformed

    private void btnTillbakaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaProjektActionPerformed
        this.dispose();
        Meny nyMeny = new Meny(idb, aid, avdid);
        nyMeny.setVisible(true);
    }//GEN-LAST:event_btnTillbakaProjektActionPerformed

    private void btnFiltreraStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltreraStatusActionPerformed
        FiltreraStatus filtreraStatusFonster = new FiltreraStatus(idb, aid, avdid);
        filtreraStatusFonster.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnFiltreraStatusActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllaProjekt;
    private javax.swing.JButton btnAvdProjekt;
    private javax.swing.JButton btnFiltreraStatus;
    private javax.swing.JButton btnHallbarMalProjekt;
    private javax.swing.JButton btnLandProjekt;
    private javax.swing.JButton btnMinaProjekt;
    private javax.swing.JButton btnSamarbetsPartnersProjekt;
    private javax.swing.JButton btnSokAvdProjDatum;
    private javax.swing.JButton btnTillbakaProjekt;
    private javax.swing.JLabel lblProjekt;
    // End of variables declaration//GEN-END:variables
}
