/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024grupp18;

import oru.inf.InfDB;

/**
 *
 * @author alex
 */
public class ProjektStatistik extends javax.swing.JFrame {
    private InfDB idb;
    private String aid;
    private String avdid;

    /**
     * Creates new form ProjektStatistik
     */
    public ProjektStatistik(InfDB idb, String aid, String avdid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        this.avdid = avdid;
        this.setLocationRelativeTo(null);

        try {
            String sqlFragaPagaendeProj = "SELECT SUM(kostnad) AS kostnadPagaende FROM projekt JOIN anstalld ON anstalld.aid = projekt.projektchef WHERE status = 'Pågående' AND anstalld.aid = " + aid + "";
            String pagaendeProjKostnad = idb.fetchSingle(sqlFragaPagaendeProj);
            tfKostnadPagaendeProj.setText(pagaendeProjKostnad);
            tfKostnadPagaendeProj.setEditable(false);
            lblKostnadPagaendeProj.requestFocus();

            String sqlFragaPlanProj = "SELECT SUM(kostnad) AS kostnadPlanerade FROM projekt JOIN anstalld ON anstalld.aid = projekt.projektchef WHERE status = 'Planerat' AND anstalld.aid = " + aid + "";
            String planProjKostnad = idb.fetchSingle(sqlFragaPlanProj);
            tfKostnadPlanProj.setText(planProjKostnad);
            tfKostnadPlanProj.setEditable(false);
            lblKostnadPlanProj.requestFocus();

            String sqlFragaAvslutProj = "SELECT SUM(kostnad) AS kostnadAvslutade FROM projekt JOIN anstalld ON anstalld.aid = projekt.projektchef WHERE status = 'Avslutat' AND anstalld.aid = " + aid + "";
            String avslutProjKostnad = idb.fetchSingle(sqlFragaAvslutProj);
            tfKostnadAvslutProj.setText(avslutProjKostnad);
            tfKostnadAvslutProj.setEditable(false);
            lblKostnadAvslutProj.requestFocus();

            String sqlFragatotKostnadMinaProj = "SELECT SUM(kostnad) AS totKostnad FROM projekt JOIN anstalld ON anstalld.aid = projekt.projektchef WHERE anstalld.aid = " + aid + "";
            String totKostnadMinaProj = idb.fetchSingle(sqlFragatotKostnadMinaProj);
            tfTotKostnadMinaProj.setText(totKostnadMinaProj);
            tfTotKostnadMinaProj.setEditable(false);
            lblTotKostnadMinaProj.requestFocus();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKostnadPagaendeProj = new javax.swing.JLabel();
        lblProjektStatistik = new javax.swing.JLabel();
        tfKostnadPagaendeProj = new javax.swing.JTextField();
        lblKostnadPlanProj = new javax.swing.JLabel();
        tfKostnadPlanProj = new javax.swing.JTextField();
        lblKostnadAvslutProj = new javax.swing.JLabel();
        tfKostnadAvslutProj = new javax.swing.JTextField();
        lblTotKostnadMinaProj = new javax.swing.JLabel();
        tfTotKostnadMinaProj = new javax.swing.JTextField();
        btnTillbakaProjStat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKostnadPagaendeProj.setText("Total kostnad för pågående projekt ");

        lblProjektStatistik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblProjektStatistik.setText("Projektstatistik");

        lblKostnadPlanProj.setText("Total kostnad för planerade projekt");

        lblKostnadAvslutProj.setText("Total kostnad för avslutade projekt");

        lblTotKostnadMinaProj.setText("Total kostnad för alla mina projekt");

        btnTillbakaProjStat.setText("Tillbaka");
        btnTillbakaProjStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaProjStatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTillbakaProjStat)
                    .addComponent(lblProjektStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTotKostnadMinaProj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKostnadAvslutProj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKostnadPlanProj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKostnadPagaendeProj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfKostnadPagaendeProj)
                            .addComponent(tfKostnadPlanProj)
                            .addComponent(tfKostnadAvslutProj)
                            .addComponent(tfTotKostnadMinaProj, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblProjektStatistik)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKostnadPagaendeProj)
                    .addComponent(tfKostnadPagaendeProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKostnadPlanProj)
                    .addComponent(tfKostnadPlanProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKostnadAvslutProj)
                    .addComponent(tfKostnadAvslutProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotKostnadMinaProj)
                    .addComponent(tfTotKostnadMinaProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnTillbakaProjStat)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaProjStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaProjStatActionPerformed
        this.dispose();
        MinaProjekt nyttMinaProjekt = new MinaProjekt(idb, aid, avdid);
        nyttMinaProjekt.setVisible(true);
    }//GEN-LAST:event_btnTillbakaProjStatActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbakaProjStat;
    private javax.swing.JLabel lblKostnadAvslutProj;
    private javax.swing.JLabel lblKostnadPagaendeProj;
    private javax.swing.JLabel lblKostnadPlanProj;
    private javax.swing.JLabel lblProjektStatistik;
    private javax.swing.JLabel lblTotKostnadMinaProj;
    private javax.swing.JTextField tfKostnadAvslutProj;
    private javax.swing.JTextField tfKostnadPagaendeProj;
    private javax.swing.JTextField tfKostnadPlanProj;
    private javax.swing.JTextField tfTotKostnadMinaProj;
    // End of variables declaration//GEN-END:variables
}
