/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024grupp18;

import oru.inf.InfDB;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author ellenor
 */
public class Samarbetspartner extends javax.swing.JFrame {

    private InfDB idb;
    private String aid;
    private String avdid;

    /**
     * Creates new form Samarbetspartner
     */
    public Samarbetspartner(InfDB idb, String aid, String avdid) {
        initComponents();
        this.idb = idb;
        this.aid = aid;
        this.avdid = avdid;
        this.setLocationRelativeTo(null);
        fyllCBVäljSamarbetspartner();

    }

    // Lägger till alla samarbetspartner i combobox
    public void fyllCBVäljSamarbetspartner() {
        try {
            String sqlFraga = "SELECT DISTINCT namn FROM partner";
            System.out.println(sqlFraga);
            ArrayList<String> partnerLista = idb.fetchColumn(sqlFraga);

            for (String enPartner : partnerLista) {
                cbValjSamarbetspartner.addItem(enPartner);
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbValjSamarbetspartner = new javax.swing.JComboBox<>();
        btnTillbakaSamarbetspartner = new javax.swing.JButton();
        btnSparAndringarSam = new javax.swing.JButton();
        lblProjektIDSam = new javax.swing.JLabel();
        lblNamnSam = new javax.swing.JLabel();
        lblKontaktpersonSam = new javax.swing.JLabel();
        lblEpostSam = new javax.swing.JLabel();
        lblTnrSam = new javax.swing.JLabel();
        lblAdressSam = new javax.swing.JLabel();
        lblBranchSam = new javax.swing.JLabel();
        lblStadSam = new javax.swing.JLabel();
        tfProjektIDSam = new javax.swing.JTextField();
        tfNamnSam = new javax.swing.JTextField();
        tfKontaktpersonSam = new javax.swing.JTextField();
        tfEpostSam = new javax.swing.JTextField();
        tfTnrSam = new javax.swing.JTextField();
        tfAdressSam = new javax.swing.JTextField();
        tfBranchSam = new javax.swing.JTextField();
        tfStadSam = new javax.swing.JTextField();
        btnLaggTillPartner = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Samarbetspartner");

        cbValjSamarbetspartner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj samarbetspartner" }));
        cbValjSamarbetspartner.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbValjSamarbetspartnerPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btnTillbakaSamarbetspartner.setText("Tillbaka");
        btnTillbakaSamarbetspartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaSamarbetspartnerActionPerformed(evt);
            }
        });

        btnSparAndringarSam.setText("Spara ändringar");
        btnSparAndringarSam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparAndringarSamActionPerformed(evt);
            }
        });

        lblProjektIDSam.setText("Projekt-ID");

        lblNamnSam.setText("Namn");

        lblKontaktpersonSam.setText("Kontaktperson");

        lblEpostSam.setText("E-post");

        lblTnrSam.setText("Telefonnummer");

        lblAdressSam.setText("Adress");

        lblBranchSam.setText("Branch");

        lblStadSam.setText("Stad");

        btnLaggTillPartner.setText("Lägg till samarbetspartner");
        btnLaggTillPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillPartnerActionPerformed(evt);
            }
        });

        jButton1.setText("Ta bort samarbetspartner");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnTillbakaSamarbetspartner)
                        .addGap(35, 35, 35)
                        .addComponent(btnSparAndringarSam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbValjSamarbetspartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLaggTillPartner))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblProjektIDSam)
                                            .addComponent(lblNamnSam)
                                            .addComponent(lblKontaktpersonSam)
                                            .addComponent(lblEpostSam)
                                            .addComponent(lblTnrSam)
                                            .addComponent(lblAdressSam)
                                            .addComponent(lblBranchSam)
                                            .addComponent(lblStadSam))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfProjektIDSam)
                                            .addComponent(tfNamnSam)
                                            .addComponent(tfKontaktpersonSam)
                                            .addComponent(tfEpostSam)
                                            .addComponent(tfTnrSam)
                                            .addComponent(tfAdressSam)
                                            .addComponent(tfBranchSam)
                                            .addComponent(tfStadSam, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbValjSamarbetspartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaggTillPartner))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektIDSam)
                    .addComponent(tfProjektIDSam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamnSam)
                    .addComponent(tfNamnSam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKontaktpersonSam)
                    .addComponent(tfKontaktpersonSam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEpostSam)
                    .addComponent(tfEpostSam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTnrSam, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTnrSam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdressSam)
                    .addComponent(tfAdressSam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBranchSam)
                    .addComponent(tfBranchSam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStadSam)
                    .addComponent(tfStadSam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbakaSamarbetspartner)
                    .addComponent(jButton1)
                    .addComponent(btnSparAndringarSam))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaSamarbetspartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaSamarbetspartnerActionPerformed
        this.toBack();
        Projekt nyttProjekt = new Projekt(idb, aid, avdid);
        nyttProjekt.setVisible(true);
        nyttProjekt.toFront();
    }//GEN-LAST:event_btnTillbakaSamarbetspartnerActionPerformed

    private void btnSparAndringarSamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparAndringarSamActionPerformed

        try {

            String projketID = tfProjektIDSam.getText();
            String namn = tfNamnSam.getText();
            String kontaktperson = tfKontaktpersonSam.getText();
            String kontaktEpost = tfEpostSam.getText();
            String telefonnummer = tfTnrSam.getText();
            String adress = tfAdressSam.getText();
            String branch = tfBranchSam.getText();
            String stad = tfStadSam.getText();

            String sqlFraga = " INSERT INTO partner WHERE pid = (pid, namn, kontaktperson, kontaktepost, telefon, adress, branch, stad) VALUES('" + projketID + "','" + namn + "', '" + kontaktperson + "', '" + kontaktEpost + "', '" + telefonnummer + "', '" + adress + "', '" + branch + "', '" + stad + "')";
            idb.insert(sqlFraga);
        } catch (Exception ex) {

            System.out.println(ex.getMessage());

        }


    }//GEN-LAST:event_btnSparAndringarSamActionPerformed

    private void cbValjSamarbetspartnerPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbValjSamarbetspartnerPopupMenuWillBecomeInvisible

        String partnerNamn = cbValjSamarbetspartner.getSelectedItem().toString();

        try {

            String sqlFraga = "SELECT * FROM partner WHERE namn = '" + partnerNamn + "'";
            System.out.println(sqlFraga);

            HashMap<String, String> partnerNamnLista = idb.fetchRow(sqlFraga);

            if (partnerNamnLista != null) {
                tfProjektIDSam.setText(partnerNamnLista.get("pid"));
                tfNamnSam.setText(partnerNamnLista.get("namn"));
                tfKontaktpersonSam.setText(partnerNamnLista.get("kontaktperson"));
                tfEpostSam.setText(partnerNamnLista.get("kontaktepost"));
                tfTnrSam.setText(partnerNamnLista.get("telefon"));
                tfAdressSam.setText(partnerNamnLista.get("adress"));
                tfBranchSam.setText(partnerNamnLista.get("branch"));
                tfStadSam.setText(partnerNamnLista.get("stad"));
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());

        }

    }//GEN-LAST:event_cbValjSamarbetspartnerPopupMenuWillBecomeInvisible

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String partnerNamn = cbValjSamarbetspartner.getSelectedItem().toString();
        try {

            String sqlFraga = " DELETE FROM partner WHERE pid = '" + partnerNamn + "'";

            // rensar textfields från uppgifter
            tfProjektIDSam.setText(" ");
            tfNamnSam.setText(" ");
            tfKontaktpersonSam.setText(" ");
            tfEpostSam.setText(" ");
            tfTnrSam.setText(" ");
            tfAdressSam.setText(" ");
            tfBranchSam.setText(" ");
            tfStadSam.setText(" ");

            // uppdaterar comboboxen
            cbValjSamarbetspartner.removeAllItems();
            fyllCBVäljSamarbetspartner();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLaggTillPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillPartnerActionPerformed
        new LaggTillSamarbetspartner(idb, aid, avdid).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnLaggTillPartnerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTillPartner;
    private javax.swing.JButton btnSparAndringarSam;
    private javax.swing.JButton btnTillbakaSamarbetspartner;
    private javax.swing.JComboBox<String> cbValjSamarbetspartner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdressSam;
    private javax.swing.JLabel lblBranchSam;
    private javax.swing.JLabel lblEpostSam;
    private javax.swing.JLabel lblKontaktpersonSam;
    private javax.swing.JLabel lblNamnSam;
    private javax.swing.JLabel lblProjektIDSam;
    private javax.swing.JLabel lblStadSam;
    private javax.swing.JLabel lblTnrSam;
    private javax.swing.JTextField tfAdressSam;
    private javax.swing.JTextField tfBranchSam;
    private javax.swing.JTextField tfEpostSam;
    private javax.swing.JTextField tfKontaktpersonSam;
    private javax.swing.JTextField tfNamnSam;
    private javax.swing.JTextField tfProjektIDSam;
    private javax.swing.JTextField tfStadSam;
    private javax.swing.JTextField tfTnrSam;
    // End of variables declaration//GEN-END:variables
}
